export const USER_LOADED = 'USER_LAODED';
export const TOGGLE_ITEM = 'TOGGLE_ITEM'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const INCEREMENT_COUNT = 'INCEREMENT_COUNT'
export const DECREMENT_COUNT = 'DECREMENT_COUNT'