export default {
  ru: 'Русский',
  uz: 'Узбекский',
  login: 'Вход',
  forMen: 'Мужчинам ',
  forWomen: 'Женщинам',
  forKids: 'Детям',
  selectLanguage: 'Выбрать язык',
  waiting: 'Ожидается доставка',
  delivered: 'Доставлено',
  order: 'Заказы',
  noFavoriteItem: 'Нет любимого предмета',
  article: 'Артикул: ',
  size: 'Размер',
  color: 'Цвет',
  overall: 'Итого:',
  aboutProduct: 'О товаре',
  upperMaterial: 'Материал верха:',
  fauxLeather: 'искусственная кожа',
  innerMaterial: 'Внутренний материал:',
  fauxFur: 'искусственный мех',
  outsoleMaterial: 'Материал подошвы:',
  thermoplasticRubber: 'термопластиковая  резина',
  shop: 'Магазин',
  nike: 'NIKE',
  nikeDescription:
    'Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться.',
  address: 'Адрес',
  phone: 'Телефон',
  workingHours: 'Режим работы',
  yourData: 'Ваши данные',
  name: 'Имя',
  familyName: 'Фамилия',
  phoneNumber: 'Номер телефона',
  checkout: 'Оформление заказа',
  shops: 'Магазины',
  myProfile: 'Мой профиль',
  favorite: 'Избранное',
  next: 'Далее',
  howToReceiveOrder: 'Выберите способ получения заказа',
  freeDelivery: 'Бесплатная доставка',
  day: ' дней',
  days: ' дней',
  city: 'Город',
  district: 'Район',
  street: 'Улица',
  home: 'Дом',
  apartment: 'Квартира',
  january: 'Январь',
  deliveryDate: 'Дата доставки',
  timeOfDelivery: 'Время доставки',
  selectPaymentMethod: 'Выберите способ оплаты',
  viaTheCard: 'Через карту',
  inCash: 'Наличными ',
  payVia: 'Оплатить через',
  pay: 'Оплатить',
  orderPrice: 'Сумма заказа',
  totalPrice: 'Общая сумма',
  sneakers: 'Кроссовки',
  boots: 'Ботинки',
  slippons: 'Слипоны',
  gumshoes: 'Кеды',
  filter: 'Фильтр',
  byPopularity: 'По популярности',
  withDiscount: 'Со скидкой',
  style: 'Стиль',
  season: 'Сезон',
  price: 'Цена',
  brand: 'Бренд',
  viewAll: 'Посмотреть все',
  newItems: 'Новинки',
  logout: 'Выйти',
  pleaseLogin: 'Пожалуйста,\n войдите в свой аккаунт.',
  today: 'Сегодня',
  tomorrow: 'Завтра',
  hours: 'Часов',
  minutes: 'Минута',
  time: 'Время',
  noItems: 'Нет продуктов',
  pickSize: 'Выбрать размер',
  byDate: 'По новинкам',
  byAscendingPrice: 'По возрастанию цену',
  byDescendingPrice: 'По убыванию цену',
  byHighRating: 'По высокий рейтинг',
  byLowRating: 'По низкий рейтинг',
};
