# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrimusMall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrimusMall

  target 'PrimusMall-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrimusMallTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PrimusMall-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrimusMall-tvOS

  target 'PrimusMall-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
